import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Sidebar from "./components/Sidebar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen flex h-screen bg-custom-linear-page">
        <Sidebar />
        <div className="flex flex-1 overflow-hidden">
          <Header />
          {children}
        </div>
        <ToastContainer />
      </body>
    </html>
  );
}
